using Discord.Commands;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace DiscordAchievementBot
{
    [Group(""), Remarks("Commands for Achievement Generator.")]
    public class AchievementGeneratorCommands : ModuleBase
    {
        //todo add proper help command
        [Command("Get", RunMode = RunMode.Async), Alias("Generate")]
        public async Task Get(string achievementName, int gamerScore, AchievementType type = AchievementType.XboxOne)
        {
            Console.WriteLine("Get");

            Discord.IUserMessage ack = await ReplyAsync("Right away, " + Context.User.Mention + "!");

            //todo add permissions for this. possibly limit only to users who have a role on the server
            string filePath = GlobalConfiguration.ImageTemporaryDirectory + "aaa" + ".png";
            filePath = Environment.ExpandEnvironmentVariables(filePath);

            ImageGeneration.GenerateImage(achievementName, gamerScore, type, filePath);

            // remove the ack once file has been generated

            // gotta be a better way for this
            List<Discord.IUserMessage> del = new List<Discord.IUserMessage>();
            del.Add(ack);

            await Context.Channel.DeleteMessagesAsync(del);

            await Context.Channel.SendFileAsync(filePath, "Generated by " + Context.User.Mention + ".");
        }

        //todo invite command
        //todo github command
        //todo about command
    }
}
