version: 1.0.{build}
image:
- Visual Studio 2017
- Ubuntu
configuration: Release
platform: Any CPU
before_build:
- >-
    dotnet restore -s https://api.nuget.org/v3/index.json -s https://www.myget.org/F/discord-net/api/v3/index.json
build:
  project: DiscordAchievementBot.sln
  verbosity: minimal
test_script:
- cmd: dotnet test .\DiscordAchievementBot.Tests\DiscordAchievementBot.Tests.csproj